#!/bin/sh
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
program_key="$repo_root/_keys/matchpot_escrow-program-keypair.json"
deploy_key="$repo_root/target/deploy/matchpot_escrow-keypair.json"

if [ ! -f "$program_key" ]; then
  echo "Missing $program_key" >&2
  echo "Restore the backed-up MatchPot program keypair before building." >&2
  exit 1
fi

mkdir -p "$repo_root/target/deploy"
cp "$program_key" "$deploy_key"
chmod 600 "$deploy_key"

cd "$repo_root"
anchor build

# Keep the browser client on the exact IDL/type generated by this program build.
cp "$repo_root/target/idl/matchpot_escrow.json" "$repo_root/packages/web/idl/matchpot_escrow.json"
cp "$repo_root/target/types/matchpot_escrow.ts" "$repo_root/packages/web/idl/matchpot_escrow.ts"
